# Generated by Django 4.0.4 on 2022-06-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='published_date',
        ),
    ]
