# Generated by Django 4.0.4 on 2022-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='shipId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
