# Generated by Django 4.0.4 on 2022-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_ship_shipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='shipId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
